default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] %>

development:
  <<: *default
  database: g_scores_development

test:
  <<: *default
  database: g_scores_test

production:
  <<: *default
  database: g_scores_production